language: python
cache: pip

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
matrix:
  fast_finish: true
  include:
    - python: 3.9
    - python: 3.8
    - python: 3.7
    - python: 3.6
    - python: 3.5

install:
 - pip install -U pip
 - pip install -U -r requirements.txt
 - pip install -U flake8
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install -U black; fi

script:
 # Static analysis
 - flake8 --statistics --count
 - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then black --check --diff .; fi

 # Dummy run
 - python bitsofpluto.py --help
 - python bitsofpluto.py --yaml data/bitsofpluto_sample.yaml --pluto data/crop_p_color2_enhanced_release.7000x7000.png -x
